name: Bug Report
description: File a bug report (if something is not working properly)
title: "[Bug] <title>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!

        Make sure you've searched [existing issues](https://github.com/trinhngocthuyen/xccache/issues) for the bug you encountered.
  - type: textarea
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see! Remember to run `xccache` with `--verbose` for more useful logs
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        💡 Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
